version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
          - VIMEO_ACCESS_TOKEN=${VIMEO_ACCESS_TOKEN}
          - VIMEO_CLIENT_ID=${VIMEO_CLIENT_ID}
          - VIMEO_CLIENT_SECRET=${VIMEO_CLIENT_SECRET}
          - MONGODB_URI=${MONGODB_URI}
          - RESET_SECRET_KEY=${RESET_SECRET_KEY}
          - GMAIL_USER=${GMAIL_USER}
          - GMAIL_PASSWORD=${GMAIL_PASSWORD}
          - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
          - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: [--auth]
    environment:
          - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
          - MONGO_INITDB_ROOT_PASSWORD=${SECRET_KEY}
    volumes:
      - '/mnt/disks/mongodb:/data/db'